
import type { Candidate, JobRequisition } from './types';

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand1',
    name: 'Alice Wonderland',
    email: 'alice@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    jobTitle: 'Software Engineer',
    stage: 'Screening',
    appliedDate: new Date('2023-10-01').toISOString(),
    lastContacted: new Date('2023-10-05').toISOString(),
    skills: ['React', 'Node.js', 'TypeScript'],
    notes: 'Promising candidate, strong technical skills.',
  },
  {
    id: 'cand2',
    name: 'Bob The Builder',
    email: 'bob@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    jobTitle: 'Product Manager',
    stage: 'Interview',
    appliedDate: new Date('2023-09-15').toISOString(),
    lastContacted: new Date('2023-10-10').toISOString(),
    skills: ['Agile', 'Roadmap Planning', 'User Research'],
    notes: 'Excellent communication skills, good fit for culture.',
  },
  {
    id: 'cand3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    jobTitle: 'UX Designer',
    stage: 'Offer',
    appliedDate: new Date('2023-10-05').toISOString(),
    lastContacted: new Date('2023-10-12').toISOString(),
    skills: ['Figma', 'Prototyping', 'User Testing'],
  },
  {
    id: 'cand4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    jobTitle: 'Software Engineer',
    stage: 'Sourced',
    appliedDate: new Date('2023-10-10').toISOString(),
    skills: ['Java', 'Spring Boot', 'Microservices'],
  },
    {
    id: 'cand5',
    name: 'Edward Scissorhands',
    email: 'edward@example.com',
    jobTitle: 'Data Scientist',
    stage: 'Hired',
    appliedDate: new Date('2023-08-01').toISOString(),
    lastContacted: new Date('2023-09-20').toISOString(),
    skills: ['Python', 'Machine Learning', 'TensorFlow'],
    notes: 'Accepted offer, onboarding next week.',
  },
  {
    id: 'cand6',
    name: 'Fiona Gallagher',
    email: 'fiona@example.com',
    jobTitle: 'Marketing Specialist',
    stage: 'Rejected',
    appliedDate: new Date('2023-09-01').toISOString(),
    lastContacted: new Date('2023-09-15').toISOString(),
    skills: ['SEO', 'Content Creation', 'Social Media'],
    notes: 'Experience not aligned with senior role requirements.',
  },
];

export const MOCK_JOB_REQUISITIONS: JobRequisition[] = [
  {
    id: 'job1',
    title: 'Senior Software Engineer (Frontend)',
    department: 'Engineering',
    location: 'Remote',
    status: 'Open',
    datePosted: new Date('2023-09-20').toISOString(),
    description: 'Join our dynamic team to build cutting-edge user interfaces for our flagship product. Extensive experience with React and TypeScript required.',
    skillsRequired: ['React', 'TypeScript', 'GraphQL', 'Next.js'],
    hiringManager: 'Jane Doe',
    priority: 'High',
  },
  {
    id: 'job2',
    title: 'Product Manager, Growth',
    department: 'Product',
    location: 'New York, NY',
    status: 'Open',
    datePosted: new Date('2023-10-01').toISOString(),
    description: 'Lead our growth initiatives by identifying new market opportunities and optimizing user acquisition funnels. Strong analytical skills needed.',
    skillsRequired: ['Product Strategy', 'Data Analysis', 'A/B Testing', 'Agile'],
    hiringManager: 'John Smith',
    priority: 'High',
  },
  {
    id: 'job3',
    title: 'UX Designer',
    department: 'Design',
    location: 'San Francisco, CA',
    status: 'On Hold',
    datePosted: new Date('2023-08-15').toISOString(),
    description: 'Create intuitive and engaging user experiences across web and mobile platforms. Portfolio showcasing strong visual and interaction design skills is a must.',
    skillsRequired: ['Figma', 'User Research', 'Prototyping', 'Usability Testing'],
    hiringManager: 'Alice Brown',
    priority: 'Medium',
  },
  {
    id: 'job4',
    title: 'Junior Backend Developer',
    department: 'Engineering',
    location: 'Remote',
    status: 'Closed',
    datePosted: new Date('2023-07-01').toISOString(),
    description: 'Assist in the development and maintenance of our backend services. Opportunity to learn and grow with a supportive team.',
    skillsRequired: ['Node.js', 'Express', 'MongoDB', 'REST APIs'],
    hiringManager: 'Jane Doe',
    priority: 'Medium',
  },
   {
    id: 'job5',
    title: 'Technical Recruiter',
    department: 'Human Resources',
    location: 'Austin, TX',
    status: 'Draft',
    datePosted: new Date().toISOString(),
    description: 'Seeking an experienced technical recruiter to help us find top talent for our rapidly growing engineering team. Must have experience recruiting for software roles.',
    skillsRequired: ['Sourcing', 'Interviewing', 'Negotiation', 'ATS Management'],
    hiringManager: 'HR Manager',
    priority: 'Medium',
  },
];
